<?php
/**
 * Created by PhpStorm.
 * User: ibrahim
 * Date: 4/29/2017
 * Time: 20:47
 */
namespace kouosl\base\components;

use Yii;
use kouosl\base\helpers\GetPath;

class View extends \yii\web\View{
    public function init(){
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function render($view, $params = [], $context = null){
        $app =  Yii::$app->id;
        $module = yii::$app->controller->module->id;
        $controller = yii::$app->controller->id;
        $moduleClass = yii::$app->controller->module->className();

       if(Yii::$app->controller !== null){
           if(strncmp($moduleClass,"kouosl",8) === 0){
               $path = yii::$app->vendorPath."/kouosl/".$module."/views/".$app."/".$controller."/".$view.".php";
               if(is_file($path)){
                   return parent::renderFile($path, $params, $context);
               }
               $path =  yii::$app->vendorPath."/kouosl/theme/views/".$module."/".$app."/".$controller."/".$view.".php";
               if(is_file($path)){
                   return parent::renderFile($path, $params, $context);
               }else{
                   return parent::render($view, $params, $context);
               }
           }elseif(strncmp($moduleClass,"backend",7)){
               $path = yii::$app->basePath."/modules/".$module."/views/".$controller."/".$view.".php";
               if(is_file($path)){
                   return parent::renderFile($path, $params, $context);
               }
               $path =  yii::$app->vendorPath."/kouosl/theme/views/".$module."/".$app."/".$controller."/".$view.".php";
               if(is_file($path)){
                   return parent::renderFile($path, $params, $context);
               }else{
                   return parent::render($view, $params, $context);
               }

           }elseif(strncmp($moduleClass,"frontend",8)){
               $path = yii::$app->basePath."/modules/".$module."/views/".$controller."/".$view.".php";
               if(is_file($path)){
                   return parent::renderFile($path, $params, $context);
               }
               $path =  yii::$app->vendorPath."/kouosl/theme/views/".$module."/".$app."/".$controller."/".$view.".php";
               if(is_file($path)){
                   return parent::renderFile($path, $params, $context);
               }else{
                   return parent::render($view, $params, $context);
               }
           }else{
               return parent::render($view, $params, $context);
           }
       }else
           return parent::render($view, $params, $context);
    }
}